#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SCRIPT_DIR="$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

FILENAME=vulkan_functions.h
OUTFILE="${SCRIPT_DIR}/src/${FILENAME}"

cat << EOF > "$OUTFILE"
// ** DO NOT EDIT **
// This file is generated by $(basename "$0")
//
// Note: contents is purely based on strings of the form vk*(). Any invalid
// entries will be due to similar names found in source files.

// clang-format off
#define FOREACH_VULKAN_DEVICE_FUNCTION(sep) \\
EOF

grep -rho '\bvk[A-Z][A-Za-z0-9]\+\b' "${SCRIPT_DIR}/src" --include \*.h --include \*.hpp --include \*.cpp --exclude ${FILENAME} | \
    grep -v PhysicalDevice | \
    sort -u | \
    sed '$ ! s/^.*$/    VULKAN_FUNCTION(\0) sep \\/' | \
    sed '$ s/^.*$/    VULKAN_FUNCTION(\0)/' \
    >> "$OUTFILE"

cat << EOF >> "$OUTFILE"

#define FOREACH_VULKAN_INSTANCE_FUNCTION(sep) \\
EOF

grep -rho '\bvk[A-Z][A-Za-z0-9]\+\b' "${SCRIPT_DIR}/src" --include \*.h --include \*.hpp --include \*.cpp --exclude ${FILENAME} | \
    grep PhysicalDevice | \
    sort -u | \
    sed '$ ! s/^.*$/    VULKAN_FUNCTION(\0) sep \\/' | \
    sed '$ s/^.*$/    VULKAN_FUNCTION(\0)/' \
    >> "$OUTFILE"

cat << EOF >> "$OUTFILE"
// clang-format on
EOF