// ** DO NOT EDIT **
// This file is generated by generate_vulkan_functions.bash
//
// Note: contents is purely based on strings of the form vk*(). Any invalid
// entries will be due to similar names found in source files.

// clang-format off
#define FOREACH_VULKAN_DEVICE_FUNCTION(sep) \
    VULKAN_FUNCTION(vkAllocateDescriptorSets) sep \
    VULKAN_FUNCTION(vkCmdBindDescriptorSets) sep \
    VULKAN_FUNCTION(vkCmdBindPipeline) sep \
    VULKAN_FUNCTION(vkCmdBuildMicromapsEXT) sep \
    VULKAN_FUNCTION(vkCmdCopyBuffer) sep \
    VULKAN_FUNCTION(vkCmdDispatch) sep \
    VULKAN_FUNCTION(vkCmdFillBuffer) sep \
    VULKAN_FUNCTION(vkCmdPipelineBarrier) sep \
    VULKAN_FUNCTION(vkCmdPipelineBarrier2) sep \
    VULKAN_FUNCTION(vkCmdPushConstants) sep \
    VULKAN_FUNCTION(vkCmdUpdateBuffer) sep \
    VULKAN_FUNCTION(vkCreateComputePipelines) sep \
    VULKAN_FUNCTION(vkCreateDescriptorPool) sep \
    VULKAN_FUNCTION(vkCreateDescriptorSetLayout) sep \
    VULKAN_FUNCTION(vkCreateMicromapEXT) sep \
    VULKAN_FUNCTION(vkCreatePipelineLayout) sep \
    VULKAN_FUNCTION(vkCreateShaderModule) sep \
    VULKAN_FUNCTION(vkDestroyDescriptorPool) sep \
    VULKAN_FUNCTION(vkDestroyDescriptorSetLayout) sep \
    VULKAN_FUNCTION(vkDestroyMicromapEXT) sep \
    VULKAN_FUNCTION(vkDestroyPipeline) sep \
    VULKAN_FUNCTION(vkDestroyPipelineLayout) sep \
    VULKAN_FUNCTION(vkDestroyShaderModule) sep \
    VULKAN_FUNCTION(vkFreeDescriptorSets) sep \
    VULKAN_FUNCTION(vkGetBufferDeviceAddress) sep \
    VULKAN_FUNCTION(vkGetMicromapBuildSizesEXT) sep \
    VULKAN_FUNCTION(vkUpdateDescriptorSets)

#define FOREACH_VULKAN_INSTANCE_FUNCTION(sep) \
    VULKAN_FUNCTION(vkGetPhysicalDeviceProperties2)
// clang-format on
